config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  root              'static_pages#home'
  get 'contact' =>  'static_pages#contact'
  get 'signup' =>   'users#new'

  resources :users do
    resources :characters
  end
  resources :characters, only: [:show, :update, :destroy] do
    put 'skill' => 'characters#skill', on: :member
    put 'items' => 'characters#items', on: :member
    put 'slot' => 'characters#slot_changed', on: :member
    put 'spell' => 'characters#spell', on: :member
    post 'level_up' => 'characters#level_up', on: :member
    get 'export' => 'characters#export', on: :member
    post 'clone' => 'characters#clone', on: :member
  end
  get 'characters' => 'characters#all_index'

  resources :rule_sets do
    resources :races do
      get 'modifiers' => 'races#modifiers', on: :member
      get 'abilities' => 'races#abilities', on: :member
    end
    resources :birthsigns do
      get 'modifiers' => 'birthsigns#modifiers', on: :member
    end
    resources :specializations
    resources :attributes, except: [:show]
    resources :skills, except: [:show]
    resources :resistances, except: [:show]
    resources :item_prototypes, except: [:show] do
      collection { post :import }
    end
    resources :spells, except: [:show]
    get 'spells/:school' => 'spells#school_index'
    get 'properties' => 'rule_sets#properties', on: :member
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' =>    'sessions#new'
  post 'login' =>   'sessions#create'
  get 'logout' => 'sessions#destroy'
  post 'auth' => 'sessions#auth'
  post 'verify' => 'sessions#verify'

  get 'templates/property_modifier_config' => 'static_pages#property_modifier_config'
  get 'templates/ability_config' => 'static_pages#ability_config'
  get 'templates/charsheet_item' => 'static_pages#charsheet_item'
  get 'templates/char_equip_slot' => 'static_pages#char_equip_slot'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def property_modifier_config
    render layout: false
  end

  def ability_config
    render layout: false
  end

  def charsheet_item
    render layout: false
  end

  def char_equip_slot
    render layout: false
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/ability_config.html.erb
<div class="ability-config">
  <a class="btn" ng-click="addAbility()">{{ newText }}</a>
  <ul>
    <li ng-repeat="ability in abilities" ng-class="{hidden: ability._destroy}">
      <input type="text"
             name="{{ nameStart }}[{{ ability.frontend_id }}][name]{{ nameEnd }}" 
             class="name"
             placeholder="Name" 
             ng-model="ability.name" 
             ng-required="true" />
      <input type="text"
             class="desc"
             placeholder="Beschreibung / Effekte"
             name="{{ nameStart }}[{{ ability.frontend_id }}][desc]{{ nameEnd }}"
             ng-model="ability.desc" 
             ng-pattern="/^[+\-\*\/]$/"
             ng-required="true"/>
      <input type="hidden" 
             name="{{ nameStart }}[{{ ability.frontend_id }}][id]{{ nameEnd }}"
             ng-value="ability.id" 
             ng-if="ability.id" />
      <input type="hidden"
             name="{{ nameStart }}[{{ ability.frontend_id }}][_destroy]{{ nameEnd }}"
             ng-if="ability._destroy"
             ng-value="ability._destroy" />
      <h3>Buffs</h3>
      <property-modifier-config mods="ability.property_modifiers"
              prop-url="propUrl"
              name-start="{{ nameStart }}[{{ ability.frontend_id }}][property_modifiers_attributes"
              name-end="]{{ nameEnd }}"
              new-text="Neuer Buff"
              delete-text="Buff löschen">
      </property-modifier-config>
      <a class="btn" ng-click="removeAbility(ability)">{{ deleteText }}</a>
    </li>
  </ul>
</div>

app/views/static_pages/char_equip_slot.html.erb
<div class="char-equip-slot-container" ng-class="slot.identifier">
  <div ng-if="!weapon">
    <%# Armor slot %>
    <div class="char-equip-slot" title="{{ slot.name }}" ng-class="slot.item ? '' : slot.key"
         ng-click="toggleMenu()">
      <div class="char-equip-slot-content">
        <span ng-if="!slot.item.image" class="equipped-item-name" title="{{ slot.item.name }}">{{ slot.item.name }}</span>
        <img ng-if="slot.item.image" ng-src="{{ slot.item.image }}" title="{{ slot.item.name }}" />
        <br />
        <%= prop_tag 'armor.png', 'slot.item.armor', alt: 'Rüstung' %>
      </div>
    </div>
    <ul class="char-equip-slot-dropdown" ng-show="showMenu">
      <li>
        <a ng-click="itemSelected(null)">-- Leer --</a>
      </li>
      <li ng-repeat="item in items[slot.key] | filter:{type:'!weapon'}">
        <a ng-click="itemSelected(item)">{{ item.name }}</a>
      </li>
    </ul>
  </div>
  <div ng-if="weapon">
    <%# Weapon slot %>
    <div class="char-weapon-slot" title="{{ slot.name }}"
         ng-click="toggleMenu()">
      <h4 class="inline char-weapon-slot-label">{{ slot.name }}</h4>
      <div class="char-weapon-data">
        <div class="padded">
          <img ng-if="slot.item.image" ng-src="{{ slot.item.image }}" title="{{ slot.item.name }}" />
          <h4 class="inline">{{ slot.item.name }}</h4>
        </div>
        <div class="weapon-properties" ng-click="$event.stopPropagation()">
          <div class="column-container clearfix padded">
            <div class="column-50">
              <%= character_property_minimal 'damage.png', 'slot.item.damage', alt: 'Schaden' %>
              <%= character_property_minimal 'condition.png', 'slot.item.condition', alt: 'Zustand', unit: '%',
                                             editable: true, on_confirm: 'updateItem(slot.item)' %>
              <%= character_property_minimal 'arrow.png', 'slot.item.arrow_dmg', alt: 'Pfeilschaden',
                                             editable: true, on_confirm: 'updateItem(slot.item)' %>
            </div>
            <div class="column-50">
              <%= character_property_minimal 'range.png', 'slot.item.range', alt: 'Reichweite' %>
              <%= character_property_minimal 'speed.png', 'slot.item.speed', alt: 'Geschwindigkeit' %>
            </div>
          </div>
          <div ng-if="slot.item">
            <div ng-if="slot.identifier == 'left_hand'">
              <%= character_property 'dice.png', 'W6-Schaden', 'char.rolled_damage_left',
                                     small: true, embedded: true, editable: true %>
            </div>
            <div ng-if="slot.identifier == 'right_hand'">
              <%= character_property 'dice.png', 'W6-Schaden', 'char.rolled_damage_right',
                                     small: true, embedded: true, editable: true %>
            </div>
            <div ng-if="slot.identifier == 'left_hand'">
              <%= character_property 'damage.png', 'Eff. Schaden', 'char.left_weapon_damage',
                                     small: true, embedded: true %>
            </div>
            <div ng-if="slot.identifier == 'right_hand'">
              <%= character_property 'damage.png', 'Eff. Schaden', 'char.right_weapon_damage',
                  small: true, embedded: true %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <ul class="char-equip-slot-dropdown" ng-show="showMenu">
      <li>
        <a ng-click="itemSelected(null)">-- Leer --</a>
      </li>
      <li ng-repeat="item in items[slot.key] | filter:{type:'weapon'}">
        <a ng-click="itemSelected(item)">{{ item.name }}</a>
      </li>
    </ul>
  </div>
</div>

app/views/static_pages/charsheet_item.html.erb
<div class="item-editor" ng-show="!item._null">
  <input class="item-quantity form-control" type="text" ng-model="item.quantity" placeholder="Anzahl" />x
  <input class="item-name form-control" type="text" ng-model="item.name"
         sf-typeahead="true" options="typeaheadOptions" datasets="itemPrototypes" placeholder="Name" />
  <%= prop_input 'weight.png', 'item.weight', alt: 'Gewicht', class: 'item-value' %>
  <%= prop_input 'armor.png', 'item.armor', alt: 'Rüstung', class: 'item-value',
                 show: 'item.type == "armor"' %>

  <select class="item-type form-control selectpicker" selectpicker=""
          ng-model="item.type">
    <option value="" label="Typ" selected="selected">Typ</option>
    <% ItemPrototype.types.keys.collect do |type| %>
      <option value="<%= type %>">
        <%= t("activerecord.attributes.item_prototype.types.#{type}") %>
      </option>
    <% end %>
  </select>
  <span ng-show="item.type == 'armor'">
    <select class="item-armor-type form-control selectpicker" selectpicker=""
            ng-model="item.armor_type">
      <option value="" label="Rüstungstyp" selected="selected">Rüstungstyp</option>
      <% ItemPrototype.armor_types.keys.collect do |type| %>
        <option value="<%= type %>">
          <%= t("activerecord.attributes.item_prototype.armor_types.#{type}") %>
        </option>
      <% end %>
    </select>
  </span>
  <span ng-show="item.type == 'armor' || item.type == 'accessory'">
    <select class="item-slot form-control selectpicker" selectpicker=""
            ng-model="item.slot">
      <option value="" label="Slot" selected="selected">Slot</option>
      <% ItemPrototype.slots.keys.collect do |slot| %>
        <option value="<%= slot %>">
          <%= t("activerecord.attributes.item_prototype.slots.#{slot}") %>
        </option>
      <% end %>
    </select>
  </span>
  <%= prop_input 'value.png', 'item.value', alt: 'Wert in Gold', class: 'item-value' %>
  <%= prop_input 'range.png', 'item.range', alt: 'Reichweite', class: 'item-value', title: '5',
                 show: 'item.type == "ranged_weapon" || item.type == "melee_weapon"' %>
  <%= prop_input 'arrow.png', 'item.arrow_dmg', alt: 'Pfeilschaden', class: 'item-value', title: 'Pfeilschaden',
                 show: 'item.type == "ranged_weapon"' %>
  <%= prop_input 'damage.png', 'item.damage', alt: 'Schaden', class: 'item-damage',
                 show: 'item.type == "ranged_weapon" || item.type == "melee_weapon"' %>
  <%= prop_input 'speed.png', 'item.speed', alt: 'Geschwindigkeit', class: 'item-value',
                 show: 'item.type == "ranged_weapon" || item.type == "melee_weapon"' %>
  <%= prop_input 'condition.png', 'item.condition', alt: 'Zustand', class: 'item-value',
                 show: 'item.type == "ranged_weapon" || item.type == "melee_weapon"' %>
  <%= prop_input 'clumsiness.png', 'item.clumsiness', alt: 'Klobigkeit', class: 'item-value',
                 show: 'item.type == "armor"' %>

  <textarea class="item-desc form-control" ng-model="item.desc" placeholder="Beschreibung">
  </textarea>
  <div class="actions">
    <button class="btn" ng-click="confirm()">OK</button>
    <button class="btn" ng-click="cancel()" title="Schließen ohne zu speichern" ng-show="item.id">
      Schließen
    </button>
    <button class="btn" ng-click="destroyItem()">Löschen</button>
    <button class="btn" ng-click="publishItem()" ng-if="!item.prototype_id">In die Datenbank</button>
    <span ng-if="item.prototype_id">
      <span class="glyphicon glyphicon-ok"></span>
      In der Datenbank
    </span>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, t('contact.title')) %>
<h1><%=t 'contact.title' %></h1>
<p>
  Morrowind PnP wurde / wird von David Bauske als Hobbyprojekt entwickelt.
</p>
<p>
  <%=t 'contact.content' %>
  <a href="mailto:david.bauske@googlemail.com">david.bauske@googlemail.com</a>.
</p>
<p>
  Morrowind ist eine Marke von Bethesda Softworks LLC. Alle Rechte liegen bei Bethesda. Dies ist ein unabhängiges Fanprojekt.
</p>
<p>
  Hintergrundbild &copy; Alexey Rudikov aka Lelek1980 (<a href="http://lelek1980.deviantart.com/art/Balmora-Aerial-view-291703424">Bild auf Deviant Art</a>)
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%=t 'home.welcome.title' %></h1>
  <h2><%=t 'home.welcome.subtitle' %></h2>

  <% if logged_in? %>
    <%= link_to 'Meine Charaktere', user_characters_path(@current_user), class: 'btn btn-lg btn-primary' %>
  <% else %>
    <div>
      <%= link_to t('sessions.signup.signup_link'), signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
    <div>oder</div>
    <div>
      <%= link_to 'Einloggen', login_path, class: 'btn btn-lg btn-primary' %>
    </div>

  <% end %>
</div>

app/views/static_pages/property_modifier_config.html.erb
<div class="modifier-config">
  <a class="btn" ng-click="addModifier()">{{ newText }}</a>
  <ul>
    <li ng-repeat="mod in modifiers" ng-class="{hidden: mod._destroy}">
      <input type="text"
             class="abbr" 
             placeholder="Kürzel" 
             ng-model="mod.property_abbr" 
             ng-change="abbrChanged(mod)"
             ng-style="mod.property_img" />
      <input type="text"
             class="operator"
             placeholder="Op"
             name="{{ nameStart }}[{{ mod.frontend_id }}][operator]{{ nameEnd }}"
             ng-model="mod.operator" 
             ng-pattern="/^[+\-\*\/]$/"
             ng-required="true"/>
      <input type="text"
             class="value"
             placeholder="Wert"
             name="{{ nameStart }}[{{ mod.frontend_id }}][value]{{ nameEnd }}"
             ng-model="mod.value"
             ng-pattern="/^[+\-]?\d+(\.(\d+)*)?$/" 
             ng-required="true" />
      <input type="hidden" 
             name="{{ nameStart }}[{{ mod.frontend_id }}][id]{{ nameEnd }}"
             ng-value="mod.id" 
             ng-if="mod.id" />
      <input type="hidden" 
             name="{{ nameStart }}[{{ mod.frontend_id }}][property_id]{{ nameEnd }}"
             ng-value="mod.property_id" />
      <input type="hidden"
             name="{{ nameStart }}[{{ mod.frontend_id }}][_destroy]{{ nameEnd }}"
             ng-if="mod._destroy"
             ng-value="mod._destroy" />
      <a class="btn" ng-click="removeModifier(mod)">{{ deleteText }}</a>
    </li>
  </ul>
</div>