config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  root              'static_pages#home'
  get 'contact' =>  'static_pages#contact'
  get 'signup' =>   'users#new'

  resources :users do
    resources :characters
  end
  resources :characters, only: [:show, :update, :destroy] do
    put 'skill' => 'characters#skill', on: :member
    put 'items' => 'characters#items', on: :member
    put 'slot' => 'characters#slot_changed', on: :member
    put 'spell' => 'characters#spell', on: :member
    post 'level_up' => 'characters#level_up', on: :member
    get 'export' => 'characters#export', on: :member
    post 'clone' => 'characters#clone', on: :member
  end
  get 'characters' => 'characters#all_index'

  resources :rule_sets do
    resources :races do
      get 'modifiers' => 'races#modifiers', on: :member
      get 'abilities' => 'races#abilities', on: :member
    end
    resources :birthsigns do
      get 'modifiers' => 'birthsigns#modifiers', on: :member
    end
    resources :specializations
    resources :attributes, except: [:show]
    resources :skills, except: [:show]
    resources :resistances, except: [:show]
    resources :item_prototypes, except: [:show] do
      collection { post :import }
    end
    resources :spells, except: [:show]
    get 'spells/:school' => 'spells#school_index'
    get 'properties' => 'rule_sets#properties', on: :member
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' =>    'sessions#new'
  post 'login' =>   'sessions#create'
  get 'logout' => 'sessions#destroy'
  post 'auth' => 'sessions#auth'
  post 'verify' => 'sessions#verify'

  get 'templates/property_modifier_config' => 'static_pages#property_modifier_config'
  get 'templates/ability_config' => 'static_pages#ability_config'
  get 'templates/charsheet_item' => 'static_pages#charsheet_item'
  get 'templates/char_equip_slot' => 'static_pages#char_equip_slot'
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  helper PdfHelper

  before_action :logged_in_user
  before_action :set_character, only: [ :show, :update, :destroy, :skill, :items, :slot_changed, :spell, :level_up, :export, :clone ]
  before_action :permitted_user, except: :all_index
  before_action :write_allowed, only: [ :new, :create, :update, :destroy, :skill, :items, :slot_changed, :spell, :level_up, :clone ]

  layout 'with_sidebar'

  def index
    @characters = @user.characters
  end

  def all_index
    if current_user.has_role?(:gm)
      @characters = Character.all
      @user = current_user
    else
      redirect_to root_url, status: 403
    end
  end

  def new
    # @type @character [Character]
    @character = @user.characters.new
    @character.rule_set = RuleSet.latest
  end

  def create
    @character = @user.characters.build(char_params)
    if @character.save
      redirect_to user_character_url(@user, @character)
    else
      render 'new'
    end
  end

  def show
    respond_to do |format|
      format.html { render layout: 'charsheet' }
      format.json { render json: char_to_json(@character) }
      format.pdf { render :show }
    end
  end

  def update
    t_update = 0
    t_render = 0
    total = Benchmark.measure do
      success = false
      t_update = Benchmark.measure do
        success = @character.update_attributes(char_params)
      end
      t_render = Benchmark.measure do
      if success
        respond_to do |format|
          format.html { redirect_to @character }
          format.json { render json: char_to_json(@character) }
        end
      else
        respond_to do |format|
          format.html { redirect_to @character }
          format.json { render json: char_to_json(@character), status: 500 }
        end
      end
      end
    end
    logger.warn("##### Update: #{(t_update.real*1000).to_i}ms")
    logger.warn("##### Render: #{(t_render.real*1000).to_i}ms")
    logger.warn("##### Update + Render: #{(total.real*1000).to_i}ms")
  end

  def destroy
    @character.destroy
    redirect_to user_characters_url(@user)
  end

  def skill
    skill_id = params[:skill_id]
    delta = params[:delta]
    if skill_id && delta
      if @character.change_skill(skill_id, delta)
        @character.save
        #@character.partial_update!
      else
        flash[:danger] = 'Modifying the Skill failed.'
      end
    else
      flash[:danger] = 'skill_id or delta missing!'
    end
    respond_to do |format|
      format.html { redirect_to @character }
      format.json { render json: char_to_json(@character) }
    end
  end

  def items
    # Create, update or delete item
    if (item_id = item_params[:id])
      item = @character.items.find item_id
      if item_params[:_destroy]
        success = @character.items.delete item
      else
        success = item.update_attributes item_params
      end
    else
      item = @character.items.new(item_params)
      success = item.save!
    end

    if success
      # The Character's items changed -> save it
      @character.save!
    end

    respond_to do |format|
      format.html { redirect_to @character }
      format.json { render json: char_to_json(@character) }
    end
  end

  def slot_changed
    if (slot = @character.slots.detect {|slot| slot.id == params[:slot_id]})
      if params[:item_id]
        slot.item = @character.items.find params[:item_id]
      else
        slot.item = nil
      end
      @character.save!
    end

    respond_to do |format|
      format.html { redirect_to @character }
      format.json { render json: char_to_json(@character) }
    end
  end

  def spell
    if (spell_id = params[:spell_id])
      if params[:perform] == 'add'
        unless @character.spells.where(id: spell_id).exists?
          @character.spells << Spell.find(spell_id)
        end
      elsif params[:perform] == 'destroy'
        @character.spells.delete(@character.spells.find(spell_id))
      else
        redirect_to root_url, status: 400
        return
      end
      @character.save!
    end

    respond_to do |format|
      format.html { redirect_to @character }
      format.json { render json: char_to_json(@character) }
    end
  end

  def level_up
    attributes = params[:attributes].
        map { |abbr| @character.property(abbr) }.select { |p| p != nil }
    if @character.level_count < 10 || attributes.length != 3
      redirect_to root_url, status: 400
    end

    @character.level_up attributes

    @character.save!

    respond_to do |format|
      format.html { redirect_to @character }
      format.json { render json: char_to_json(@character) }
    end
  end

  def export
    @use_colored_attributes = export_params[:color_attributes]
    @item_group_spacing = export_params[:item_group_spacing].to_i
    @spell_group_spacing = export_params[:spell_group_spacing].to_i

    @filename = "#{@character.name} - Charsheet.pdf"

    respond_to do |format|
      format.html { render :export }
      format.pdf { render :export }
    end
  end

  def clone
    p "Starting to clone"
    copy = @character.deep_copy
    unless copy.save
      flash[:danger] = 'Klonen fehlgeschlagen :/'
    end

    redirect_to request.referer
  end

  private
    def char_params
      params.require(:character).permit(
          :name, :race_id, :rule_set_id, :birthsign_id,
          :specialization_id, :image, :delete_image,
          :fav_attribute1_id, :fav_attribute2_id,
          :health, :mana, :stamina,
          :mana_mult_buff, :wounds,
          :wounds_head, :wounds_arm, :wounds_torso, :wounds_belly, :wounds_leg,
          :rolled_damage_left, :rolled_damage_right,
          :armor_buff, :damage_incoming,
          :offensive_buff, :defensive_buff, :evasion_buff,
          :initiative_roll, :speed_buff, :notes, :level, :level_count,
          :max_health, :location, :day, :month,
          character_properties_attributes:
              [:id, :points_buff, :points_gained, :order, :skill_type,
               :points_offensive, :points_defensive],
          items_attributes:
              [:id, :name, :desc, :quantity, :weight, :damage, :range, :armor, :slot,
               :container, :speed, :value, :type, :index, :condition, :armor_type, :arrow_dmg])
    end

    def item_params
      params.require(:item).permit(
          :id, :name, :desc, :quantity, :weight, :damage, :range, :armor, :slot,
          :container, :speed, :value, :type, :index, :prototype_id, :condition,
          :armor_type, :arrow_dmg, :clumsiness, :_destroy)
    end

    def export_params
      params.permit(:color_attributes, :item_group_spacing, :spell_group_spacing)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = 'Bitte einloggen!'
        redirect_to login_url
      end
    end

    def set_character
      @character = Character.find(params[:id])
    end

    def permitted_user
      user_id = params[:user_id]
      if user_id
        @user = User.find(user_id)
      elsif @character
        @user = @character.user
      else
        flash[:danger] = 'Kein Benutzer feststellbar!'
        redirect_to root_url, status: 403
      end

      p @character

      unless current_user?(@user) || current_user.has_role?(:gm)
        flash[:danger] = 'An fremden Charakteren herumzudoktern ist verboten!'
        redirect_to root_url, status: 403
      end
    end

    def write_allowed
      if current_user.guest?
        flash[:danger] = 'Aktion für Gäste verboten!'
        redirect_to root_url, status: 403
      end
    end

    def char_to_json(char)
      Oj.dump(char.as_json, mode: :object, indent: 0)
    end
end

app/helpers/character_helper.rb
module CharacterHelper
  def character_property(icon, text, model, options = {})
    classes = 'char-property'
    classes += ' char-property-small' if options[:small]
    classes += ' char-property-embedded' if options[:embedded]
    ( "<div class=\"#{ classes }\">" +
        '<div class="property-icon">' +
          image_tag(icon, alt: options[:alt] || text) +
        '</div>' +
        "<div class=\"property-value\"  title=\"{{ #{model} | num:5 }}\"" +
          (options[:editable] ? "data-editable=\"true\" data-model=\"#{model}\" data-number=\"true\"" : '') +
          ">{{ #{model} | num }}</div>" +
        "<div class=\"property-key\" title=\"#{text}\">#{text}</div>" +
      '</div>').html_safe
  end

  def character_property_dynamic(icon, text, model, options = {})
    classes = 'char-property'
    classes += ' char-property-small' if options[:small]
    classes += ' char-property-embedded' if options[:embedded]
    unless model.is_a?(Array)
      model = [model]
    end
    html = "<div class=\"#{ classes }\">" +
        '<div class="property-icon">' +
        "<img ng-src=\"{{ #{icon} }}\" />" +
        '</div>'
    model.reverse_each do |m|
      html += "<div class=\"property-value\" title=\"{{ #{m} | num:5 }}\"" +
          (options[:editable] ? "data-editable=\"true\" data-model=\"#{m}\" data-number=\"true\"" : '') +
          ">{{ #{m} | num }}</div>"
    end

    html += "<div class=\"property-key\" title=\"{{ #{text} }}\">{{ #{text} }}</div>" +
        '</div>'
    html.html_safe
  end

  def character_property_minimal(icon, model, options = {})
    text = options[:alt] || options[:title]
    value = options[:raw_model] ? model : "{{ #{model} | num }}"
    condition = options[:condition] || model
    ( '<div class="char-property-minimal"' +
        (options[:unconditional] ? '' : " ng-if=\"#{ condition }\"") +
        (text ? " title=\"#{ text }\"" : '') +
        '>' +
        '<div class="property-icon">' +
          image_tag(icon, alt: text) +
        '</div>' +
        "<div class=\"property-value\" " +
          (options[:editable] ? "data-editable=\"true\" data-model=\"#{model}\" data-number=\"true\"" : '') +
          (options[:on_confirm] ? "on-confirm=\"#{options[:on_confirm]}\"" : '') +
          (options[:value_as_html] ? "ng-bind-html=\"#{value}\"" : '') +
        ">#{options[:value_as_html] ? '' : value} #{options[:unit]}</div>" +
      '</div>').html_safe
  end
end

app/views/characters/_char_attributes.html.erb
<div class="char-attributes">
  <div class="char-attributes-table">
    <div>
      <h4 class="icon-col"></h4>
      <h4>Attribut</h4>
      <div class="value-col" title="Startwert bei Charaktererstellung">
        <h4 class="value-col vertical">Start</h4>
      </div>
      <div class="value-col" title="Aktueller Wert ohne Buffs">
        <h4 class="value-col vertical">Wert</h4>
      </div>
      <div class="value-col" title="Temporäre Buffs">
        <h4 class="value-col vertical">Buff</h4>
      </div>
      <div class="value-col" title="Aktueller Gesamtwert">
        <h4 class="value-col vertical">Atm</h4>
      </div>
    </div>
    <div class="char-attribute" ng-repeat="attr in char.attributes">
      <div>
        <img ng-src="{{ attr.icon }}" alt="{{ attr.name }}" />
      </div>
      <h4 class="inline">{{ attr.name }}
        <span class="multipliers">{{ formatMultiplier(attr.multiplier) }}</span>
      </h4>
      <div>{{ attr.points_base }}</div>
      <div class="value-col" editable="true" model="attr.points_gained"
           number="true" offset="attr.points_base">
        {{ attr.points_base + attr.points_gained }}
      </div>
      <div data-editable="true" model="attr.points_buff" number="true">
        {{ attr.points_buff }}
      </div>
      <div>{{ attr.points }}</div>
      <button class="btn-wood level-up-attribute-btn" type="button" ng-click="addLevelUpAttribute(attr)"
              ng-if="char.level_up_mode && levelUpAttributes.length < 3 && !attr.levelUpSelected">
        +{{ attr.points_to_add }}
      </button>
    </div>
  </div>
</div>

app/views/characters/_char_equip.html.erb
<!--<div class="char-equip" ng-class="char.specialization.name">-->
<div class="char-equip">
  <!--<img ng-src="{{ char.specialization.avatar }}" alt="{{ char.specialization.name }}" />-->
  <div ng-repeat="slot in char.slots">
    <char-equip-slot slot="slot" char="char" items="char.itemsBySlot"
                     index="{{ 400 - $index }}"
                     weapon="slot.key == 'hand' && slot.identifier != 'shield_hand'"
                     on-item-selected="itemSelected(slot, item)"
                     on-update-item="updateItem(item)">
    </char-equip-slot>
  </div>
  <div class="char-armor-box">
    <h4 class="inline">HP-Verlust</h4>
    <div class="char-property-group">
      <%= character_property 'armor_buff.png', 'Rüstungsbuff', 'char.armor_buff',
                             small: true, editable: true %>
      <%= character_property 'armor.png', 'Gesamtrüstung', 'char.total_armor', small: true %>
      <%= character_property 'damage.png', 'Schaden Eingang', 'char.damage_incoming',
                             editable: true, small: true %>
      <%= character_property 'blood-drop-icon.png', 'HP-Verlust', 'char.hp_loss', small: true %>
    </div>
  </div>
  <div class="char-hand-to-hand-box">
    <h4 class="inline">Faustkampf-Schaden</h4>
    <div class="char-property-group">
      <%= character_property 'stamina.png', 'Gegen Ausdauer', 'char.hand_to_hand_damage_stamina', small: true %>
      <%= character_property 'blood-drop-icon.png', 'Gegen HP', 'char.hand_to_hand_damage_hp', small: true %>
    </div>
  </div>
  <div class="char-initiative-box">
    <h4 class="inline">Initiative</h4>
    <div class="char-property-group">
      <%= character_property 'dice.png', 'W6', 'char.initiative_roll', small: true, editable: true %>
      <%= character_property 'initiative.png', 'Initiative', 'char.initiative', small: true %>
    </div>
  </div>
  <div class="char-speed-box">
    <h4 class="inline">Laufweg</h4>
    <div class="char-property-group">
      <%= character_property 'feet_buff.png', 'Buff', 'char.speed_buff', small: true, editable: true %>
      <%= character_property 'feet.png', 'Laufweg 1', 'char.speed', small: true %>
      <%= character_property 'feet.png', 'Laufweg 2', 'char.speed_2', small: true %>
    </div>
  </div>
</div>

app/views/characters/_char_items.html.erb
<div class="char-items" ng-init="itemTypeFilter = '!invalid'">
  <div>
    <div class="btn-group" button-group="true" model="itemTypeFilter"
         on-change="cancelItemEdit()">
      <button type="button" class="btn active" data-value="!invalid">Alle</button>
      <button type="button" class="btn" data-value="melee_weapon">Nahkampf</button>
      <button type="button" class="btn" data-value="ranged_weapon">Fernkampf</button>
      <button type="button" class="btn" data-value="armor">Rüstung</button>
      <button type="button" class="btn" data-value="consumable">Verbrauch</button>
      <button type="button" class="btn" data-value="accessory">Kleidung</button>
      <button type="button" class="btn" data-value="generic">Sonst</button>
    </div>
  </div>
  <div class="flex-row flex-row--centered flex-row--with-spacing">
    <div class="flex-grow flex-grow--zero-basis">
      <select class="items-sort form-control no-margin"
              ng-model="itemOrder" title="Sortieren">
        <option value="manual" label="Manuell" selected="selected">Manuell</option>
        <option value="name" label="Nach Namen">Nach Namen</option>
        <option value="weight" label="Nach Gewicht">Nach Gewicht</option>
        <option value="value" label="Nach Wert">Nach Wert</option>
      </select>
    </div>
    <div class="flex-grow flex-grow--zero-basis">
      <label class="checkbox inline" for="hideEmpty">
        <input type="checkbox" ng-model="hideEmpty" id="hideEmpty" />
        <span style="font-size: 15px;">Leere Items verstecken</span>
      </label>
    </div>
  </div>
  <div ng-if="itemPrototypesEngine">
    <item-editor item="editingItem"
                 item-prototypes="itemPrototypesEngine"
                 publish-url="<%= rule_set_item_prototypes_path(@character.rule_set, format: :json) %>"
                 on-destroy="destroyItem(item)" on-change="updateItem(item)" on-cancel="cancelItemEdit(item)">
    </item-editor>
  </div>
  <div ng-show="itemTypeFilter == '!invalid'">
    <%= render 'inventory_container',
               collection: 'container.items',
               searchTerm: 'searchStrings[container.name]',
               itemType: 'null' %>
  </div>
  <div ng-repeat="itemType in itemTypes" ng-show="itemTypeFilter == itemType.id">
    <%= render 'inventory_container',
               collection: 'container.itemsByType[itemType.id]',
               searchTerm: 'searchStrings[container.name]',
               itemType: 'itemType.id' %>
  </div>
</div>

app/views/characters/_char_notes.html.erb
<div class="char-notes">
  <div class="row">
    <div class="col-sm-5 padding-sm">
      <div class="char-property" title="Ort">
        <div class="property-icon">
          <%= image_tag 'location.png', alt: 'Ort' %>
        </div>
        <div class="property-key" editable="true" model="char.location"
             title="{{ char.location }}">
          {{ char.location }}
        </div>
      </div>
    </div>
    <div class="col-sm-2 padding-sm">
      <div class="char-property" title="Datum">
        <div class="property-icon">
          <%= image_tag 'calendar.png', alt: 'Datum' %>
        </div>
        <div class="property-key" editable="true" model="char.day" number="true">
          {{ char.day }}.
        </div>
      </div>
    </div>
    <div class="col-sm-5 padding-sm">
      <select ng-model="char.month" class="form-control charsheet-select"
              selectpicker="" title="Monat">
        <% [:january, :february, :march, :april, :may, :june, :july,
            :august, :september, :october, :november, :december].each do |month| %>
          <option value="<%= month %>"><%= t("months.#{month}") %></option>
        <% end %>
      </select>
    </div>
  </div>
  <text-angular ng-model="char.notes" ng-model-options="{updateOn: 'blur'}"></text-angular>
</div>

app/views/characters/_char_resis.html.erb
<div class="char-resis">
  <div class="char-resis-table">
    <div>
      <h4 class="icon-col"></h4>
      <h4>Resistenz</h4>
      <div class="value-col" title="Startwert">
        <h4 class="value-col vertical">Start</h4>
      </div>
      <div class="value-col" title="Temporäre Buffs">
        <h4 class="value-col vertical">Buff</h4>
      </div>
      <div class="value-col" title="Aktueller Gesamtwert">
        <h4 class="value-col vertical">Wert</h4>
      </div>
      <div class="value-col" title="Eingehender Schaden">
        <%= image_tag 'damage.png', class: 'icon-small', alt: 'Eingehender Schaden' %>
      </div>
      <div class="value-col" title="HP-Verlust">
        <%= image_tag 'blood-drop-icon.png', class: 'icon-small', alt: 'HP-Verlust' %>
      </div>
    </div>
    <div>
      <div class="icon-col">
        <%= image_tag 'armor.png', alt: 'Physisch' %>
      </div>
      <h4 class="inline">Physisch</h4>
      <div class="value-col"></div>
      <div class="value-col" data-editable="true" data-model="char.armor_buff" data-number="true">{{ char.armor_buff }}</div>
      <div class="value-col">{{ char.total_armor | num }}</div>
      <div class="value-col" data-editable="true" data-model="char.damage_incoming" data-number="true">{{ char.damage_incoming }}</div>
      <div class="value-col" ng-click="takeDamage(char.hp_loss)"
           ng-class="{'damage-button': char.hp_loss > 0}"
           ng-mouseenter="physHover = true" ng-mouseleave="physHover = false">
        {{ physHover && char.hp_loss > 0 ? '-' + Math.ceil(char.hp_loss) : char.hp_loss | num }}
      </div>
    </div>
    <div ng-repeat="resi in char.resistances">
      <div class="icon-col">
        <img ng-src="{{ resi.icon }}" ng-if="resi.icon" alt="{{ resi.name }}" />
      </div>
      <h4 class="inline">{{ resi.name | stripResistance }}</h4>
      <div class="value-col">{{ resi.points_base }}%</div>
      <div class="value-col" data-editable="true" data-model="resi.points_buff" data-number="true">{{ resi.points_buff }}%</div>
      <div class="value-col">{{ resi.points }}%</div>
      <div class="value-col" data-editable="true" data-model="resi.dmg" data-number="true">{{ resi.dmg || 0 }}</div>
      <div class="value-col" ng-click="takeDamage(resiHpLoss(resi))"
           ng-class="{'damage-button':resiHpLoss(resi) > 0}"
           ng-mouseenter="resi.hover = true" ng-mouseleave="resi.hover = false">
        {{ resi.hover && resiHpLoss(resi) > 0 ? '-' + Math.ceil(resiHpLoss(resi)) : resiHpLoss(resi) }}
      </div>
    </div>
  </div>
</div>

app/views/characters/_char_skills.html.erb
<% {major: 'Hauptskills', minor: 'Nebenskills', other: 'Andere Skills'}.each do |key,name| %>
  <div class="char-skills">
    <h4 class="skill-heading skill-name"><%= name %></h4>
    <h4 class="skill-heading skill-value">Start</h4>
    <h4 class="skill-heading skill-value">Wert</h4>
    <h4 class="skill-heading skill-value">Buff</h4>
    <h4 class="skill-heading skill-value">Atm</h4>
    <div class="char-skills-container" data-as-sortable="skillControlListeners"
         data-ng-model="char.sortedSkills['<%= key %>']"
         data-skill-type="<%= key %>" data-max="<%= @character.rule_set.skill_type_max(key) %>">
      <div class="char-skill" ng-repeat="skill in char.sortedSkills['<%= key %>']"
           data-as-sortable-item="true">
        <div data-as-sortable-item-handle="true">
          <img class="icon-col non-daggable" ng-src="{{ skill.icon }}" alt="{{ skill.name }}" />
          <div class="name-col">
            <span class="multipliers">{{ formatMultiplier(skill.multiplier) }}</span>
            {{ skill.name }}
          </div>
          <div class="value-col">{{ skill.points_base }}</div>
          <div class="value-col" editable="true" model="skill.points_gained"
               number="true" offset="skill.points_base">
            {{ skill.points_base + skill.points_gained }}
          </div>
          <div class="value-col" editable="true" model="skill.points_buff" number="true">
            {{ skill.points_buff }}
          </div>
          <div class="value-col">{{ skill.points }}</div>
          <div class="btn-col">
            <button type="button" class="skill-btn" title="Skill erhöhen"
                    ng-click="modifySkill(skill, 1)">+</button>
            <button type="button" class="skill-btn" title="Skill vermindern"
                    ng-click="modifySkill(skill, -1)">-</button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/characters/_inventory_container.html.erb
<div class="item-container" ng-repeat="container in char.containers"
     as-sortable="itemControlListeners" ng-model="<%= collection %>"
     container="{{ container.key }}">
  <div>
    <h3 class="inline">{{ container.name }}</h3>
      <span class="container-weight prop">
        <%= image_tag 'weight.png', alt: 'Traglast', title: 'Traglast' %>
        <span ng-class="{'text-danger': char['encumberance_from_' + container.key] >= 5,
                         'text-warning': char['encumberance_from_' + container.key] > 0}"
              title="{{ char['encumberance_from_' + container.key] }} Behinderungen">
          <span title="{{ container.weight | num:5 }}">{{ container.weight | num }}</span>
          / {{ container.max_weight | num }}
        </span>
      </span>
    <input type="search" placeholder="Suchen ..." ng-model="<%= searchTerm %>"
           class="form-control container-search" />
  </div>
  <button class="item-placeholder" ng-click="addItem(container, <%= itemType %>, $event)">
    Neues Item
  </button>
  <%= render 'inventory_item',
             collection: "#{collection} | filterItems:#{searchTerm}" %>
  <button class="item-placeholder" ng-click="addItem(container, <%= itemType %>, $event)">
    Neues Item
  </button>
</div>
<div class="clear"></div>

app/views/characters/export.html.erb
<h1>PDF-Generator: <%= @character.name %></h1>
<%= form_tag export_character_path(@character, format: :pdf), method: :get, target: '_blank' do %>
  <%= label_tag :color_attributes, class: 'checkbox inline' do %>
    <%= check_box_tag :color_attributes, '1', true %>
    <span>Attribute und zugehörige Skills farblich markieren</span>
  <% end %>

  <%= label_tag :item_group_spacing, 'Leerzeilen zwischen Itemgruppen im Inventar' %>
  <%= number_field_tag :item_group_spacing, '1', min: 0, max: 50, class: 'form-control' %>

  <%= label_tag :spell_group_spacing, 'Leerzeilen zwischen Zaubersprüchen im Zauberbuch' %>
  <%= number_field_tag :spell_group_spacing, '1', min: 0, max: 50, class: 'form-control' %>

  <button type="submit" class="btn">PDF generieren</button>
<% end %>

app/views/characters/show.html.erb
<% provide(:title, @character.name) %>

<div class="charsheet" ng-controller="CharsheetController"
     ng-init='init(
      "<%= character_path(@character, format: :json) %>",
      "<%= skill_character_path(@character, format: :json) %>",
      "<%= items_character_path(@character, format: :json) %>",
      "<%= slot_character_path(@character, format: :json) %>",
      "<%= spell_character_path(@character, format: :json) %>",
      "<%= level_up_character_path(@character, format: :json) %>",
      {
        "attributes": "<%= rule_set_attributes_path(@character.rule_set, format: :json) %>",
        "races": "<%= rule_set_races_path(@character.rule_set, format: :json) %>",
        "birthsigns": "<%= rule_set_birthsigns_path(@character.rule_set, format: :json) %>",
        "specializations": "<%= rule_set_specializations_path(@character.rule_set, format: :json) %>",
        "item_prototypes": "<%= rule_set_item_prototypes_path(@character.rule_set, format: :json) %>",
        "spells": "<%= rule_set_spells_path(@character.rule_set, format: :json) %>"
      })'>
  <div class="charsheet-col">
    <%= render 'char_base' %>
    <%= render 'char_attributes' %>
    <%= render 'char_weapon_skills' %>
  </div>
  <div class="charsheet-col-small">
    <%= render 'char_resis' %>
    <%= render 'char_skills' %>
  </div>
  <div class="charsheet-col-large">
    <%= render 'char_equip' %>
    <%= render 'char_items' %>
  </div>
  <div class="charsheet-col">
    <%= render 'char_spells' %>
    <%= render 'char_notes' %>
  </div>
</div>