config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  root              'static_pages#home'
  get 'contact' =>  'static_pages#contact'
  get 'signup' =>   'users#new'

  resources :users do
    resources :characters
  end
  resources :characters, only: [:show, :update, :destroy] do
    put 'skill' => 'characters#skill', on: :member
    put 'items' => 'characters#items', on: :member
    put 'slot' => 'characters#slot_changed', on: :member
    put 'spell' => 'characters#spell', on: :member
    post 'level_up' => 'characters#level_up', on: :member
    get 'export' => 'characters#export', on: :member
    post 'clone' => 'characters#clone', on: :member
  end
  get 'characters' => 'characters#all_index'

  resources :rule_sets do
    resources :races do
      get 'modifiers' => 'races#modifiers', on: :member
      get 'abilities' => 'races#abilities', on: :member
    end
    resources :birthsigns do
      get 'modifiers' => 'birthsigns#modifiers', on: :member
    end
    resources :specializations
    resources :attributes, except: [:show]
    resources :skills, except: [:show]
    resources :resistances, except: [:show]
    resources :item_prototypes, except: [:show] do
      collection { post :import }
    end
    resources :spells, except: [:show]
    get 'spells/:school' => 'spells#school_index'
    get 'properties' => 'rule_sets#properties', on: :member
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' =>    'sessions#new'
  post 'login' =>   'sessions#create'
  get 'logout' => 'sessions#destroy'
  post 'auth' => 'sessions#auth'
  post 'verify' => 'sessions#verify'

  get 'templates/property_modifier_config' => 'static_pages#property_modifier_config'
  get 'templates/ability_config' => 'static_pages#ability_config'
  get 'templates/charsheet_item' => 'static_pages#charsheet_item'
  get 'templates/char_equip_slot' => 'static_pages#char_equip_slot'
end

app/models/spell.rb
class Spell < ActiveRecord::Base
  has_attached_file :image, default_url: "/images/missing.gif",
                            styles: { normal: "200x200", medium: "150x150",
                                      small: "100x100", thumb: "32x32" }

  validates :name, presence: true
  validates :rule_set, presence: true
  validates :school, presence: true
  validates :range, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage/

  validates :mana_cost, numericality: { only_integer: true }
  validates :duration, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :min_effect, numericality: true, allow_nil: true
  validates :max_effect, numericality: true, allow_nil: true

  belongs_to :rule_set

  belongs_to :school, class_name: 'Skill'
  has_and_belongs_to_many :characters

  enum range: { melee: 0, support: 1, attack: 2, song: 3 }

  def range_in_m
    { 'melee' => 2.1, 'support' => 6.5, 'attack' => 11, 'song' => 5 }[range]
  end

  def range_as_string
    range = range_in_m
    unless range.nil?
      range = "#{range} m"
    end
    range
  end

  def effect(school_value)
    unless min_effect.is_a?(Numeric) && max_effect.is_a?(Numeric)
      return nil
    end
    [min_effect, school_value / 100.0 * max_effect].max.floor
  end

  default_scope { order(:school_id, :name) }

  def as_json(options = {})
    char = options[:char]
    hash = {
      'id' => id,
      'name' => name,
      'effect' => effect(char.send(school.abbr)),
      'icon' => image.exists? ? image.url(:thumb) : nil,
      'handicap' => handicap,
      'school' => {
          'abbr' => school.abbr
      }
    }
    hash['desc'] = desc if desc
    hash['mana_cost'] = mana_cost if mana_cost
    hash['min_effect'] = min_effect.to_f if min_effect
    hash['max_effect'] = max_effect.to_f if max_effect
    hash['duration'] = duration if duration
    hash['range'] = range_in_m if range_in_m
    hash
  end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :ensure_logged_in
  before_action only: [:edit, :update, :destroy, :new] do
    ensure_role(:gm)
  end
  before_action :set_spell, only: [:edit, :update, :destroy]
  before_action :set_rule_set

  def index
    @spells = @rule_set.spells
    @schools = @rule_set.skills.where(school_of_magic: true)
  end

  def school_index
    @spells = @rule_set.spells.where(school_id: params[:school])
    @schools = @rule_set.skills.where(school_of_magic: true)
    render 'index'
  end

  def new 
    @spell = @rule_set.spells.new
  end

  def edit
  end

  def create 
    @spell = @rule_set.spells.new(spell_params)
    if @spell.save
      redirect_to rule_set_spells_url(@rule_set)
    else
      render 'new'
    end
  end

  def update
    if @spell.update_attributes(spell_params)
      redirect_to rule_set_spells_url(@rule_set)
    else
      render 'edit'
    end
  end

  def destroy
    @spell.destroy
    redirect_to rule_set_spells_url(@rule_set)
  end

  private
    def set_rule_set
      @rule_set = RuleSet.find(params[:rule_set_id])
      add_breadcrumb "Regelsatz #{@rule_set.version}", rule_set_path(@rule_set)
      add_breadcrumb 'Zaubersprüche', rule_set_spells_url(@rule_set)
    end

    def set_spell
      @spell = Spell.find(params[:id])
    end

    def spell_params
      params.require(:spell).permit(:name, :image, :rule_set_id,
                                    :desc, :range, :min_effect, 
                                    :max_effect, :school_id,
                                    :mana_cost, :duration, :handicap)
    end
end

app/helpers/spells_helper.rb
module SpellsHelper
  def format_spell_effect(spell)
    unless spell.min_effect.nil? || spell.max_effect.nil?
      if spell.min_effect == spell.max_effect
        number_to_human(spell.min_effect)
      else
        "#{number_to_human(spell.min_effect)} - #{number_to_human(spell.max_effect)}"
      end
    end
  end
end

app/views/spells/_form.html.erb
<%= form_for [@rule_set, @spell] do |f| %>
  <%= render 'shared/error_messages', model: @spell %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', placeholder: 'z.B. "Firebite"' %>

  <%= f.label :desc %>
  <%= f.text_field :desc, class: 'form-control', placeholder: 'Effekte des Zaubers, Besonderheiten' %>

  <%= f.label :image %>
  <% if @spell.image.exists? %>
    <%= image_tag @spell.image.url(:small) %>
  <% end %>
  <%= f.file_field :image, class: 'form-control' %>

  <%= f.label :mana_cost %>
  <%= f.text_field :mana_cost, class: 'form-control', placeholder: 'Manakosten in Mana :P' %>

  <%= f.label :min_effect %>
  <%= f.text_field :min_effect, class: 'form-control' %>

  <%= f.label :max_effect %>
  <%= f.text_field :max_effect, class: 'form-control' %>

  <%= f.label :duration %>
  <%= f.text_field :duration, class: 'form-control', placeholder: 'Dauer in Runden' %>

  <%= f.label :handicap %>
  <%= f.text_field :handicap, class: 'form-control', placeholder: 'Erschwernis' %>

  <%= f.label :range %>
  <%= f.select :range, [['Auf Berührung', :melee], ['Unterstützung', :support], ['Offensiv', :attack], ['Lied', :song]],
    {}, class: 'selectpicker form-control', selectpicker: '' %>

  <%= f.label :school_id %>
  <%= f.collection_select :school_id, @rule_set.skills.where(school_of_magic: true), :id, :name, {}, 
    class: 'selectpicker form-control', selectpicker: '' %>

  <%= f.submit 'Speichern', class: 'btn' %>
  <% unless @spell.new_record? %>
    <%= link_to 'Löschen', rule_set_spell_path(@rule_set, @spell),
        method: :delete,
        data: { confirm: "Willst du wirklich den Zauberspruch #{@spell.name} löschen?" },
        class: 'btn' %>
  <% end %>
<% end %>

app/views/spells/edit.html.erb
<h1>Zauberspruch bearbeiten</h1>

<%= render 'form' %>

app/views/spells/index.html.erb
<h1>Zaubersprüche</h1>

<% if current_user.has_role?(:gm) %>
  <%= link_to "Neuer Zauberspruch", new_rule_set_spell_path(@rule_set), class: 'btn' %>
<% end %>

<div class="actions">
  <div class="btn-group">
    <%= link_to 'Alle', rule_set_spells_path(@rule_set), class: 'btn' %>
    <% @schools.each do |school| %>
      <%= link_to school.name, rule_set_spell_path(@rule_set, school), class: 'btn' %>
    <% end %>
  </div>
</div>

<div class="spells-display">
  <% @spells.group_by { |s| s.school }.each do |school,spells| %>
    <h3><%= school.name %></h3>
    <div class="spells-table">
      <% spells.each do |spell| %>
        <%= link_if_permitted edit_rule_set_spell_path(@rule_set, spell), :gm, class: 'spell-display' do%>
          <div class="spell-image">
            <% if spell.image.exists? %>
              <img src="<%= spell.image.url(:thumb) %>" />
            <% end %>
          </div>
          <div class="spell-text">
            <h4 title="<%= spell.name %>"><%= spell.name %></h4>
            <p title="<%= spell.desc %>"><%= spell.desc %></p>
          </div>
          <div class="spell-checks">
            <%= image_tag spell.school.check1.icon.url(:thumb), title: spell.school.check1.name %>
            <%= image_tag spell.school.check2.icon.url(:thumb), title: spell.school.check2.name %>
            <%= image_tag spell.school.icon.url(:thumb), title: spell.school.name %>
          </div>
          <div class="spell-props mana">
            <%= prop_tag_server 'mana.png', spell.mana_cost, alt: "Manakosten" %>
          </div>
          <div class="spell-props range">
            <%= prop_tag_server 'range.png', spell.range_as_string, alt: "Reichweite" %>
          </div>
          <div class="spell-props effect">
            <%= prop_tag_server 'magic.png', format_spell_effect(spell), alt: "Effektstärke" %>
          </div>
          <div class="spell-props handicap">
            <%= prop_tag_server 'handicap.png', spell.handicap, alt: "Erschwernis" %>
          </div>
          <div class="spell-props duration">
            <%= prop_tag_server 'duration.png', spell.duration, alt: "Dauer in Runden" %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<% if current_user.has_role?(:gm) %>
  <%= link_to "Neuer Zauberspruch", new_rule_set_spell_path(@rule_set), class: 'btn' %>
<% end %>

app/views/spells/new.html.erb
<h1>Neuer Zauberspruch</h1>

<%= render 'form' %>