config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  root              'static_pages#home'
  get 'contact' =>  'static_pages#contact'
  get 'signup' =>   'users#new'

  resources :users do
    resources :characters
  end
  resources :characters, only: [:show, :update, :destroy] do
    put 'skill' => 'characters#skill', on: :member
    put 'items' => 'characters#items', on: :member
    put 'slot' => 'characters#slot_changed', on: :member
    put 'spell' => 'characters#spell', on: :member
    post 'level_up' => 'characters#level_up', on: :member
    get 'export' => 'characters#export', on: :member
    post 'clone' => 'characters#clone', on: :member
  end
  get 'characters' => 'characters#all_index'

  resources :rule_sets do
    resources :races do
      get 'modifiers' => 'races#modifiers', on: :member
      get 'abilities' => 'races#abilities', on: :member
    end
    resources :birthsigns do
      get 'modifiers' => 'birthsigns#modifiers', on: :member
    end
    resources :specializations
    resources :attributes, except: [:show]
    resources :skills, except: [:show]
    resources :resistances, except: [:show]
    resources :item_prototypes, except: [:show] do
      collection { post :import }
    end
    resources :spells, except: [:show]
    get 'spells/:school' => 'spells#school_index'
    get 'properties' => 'rule_sets#properties', on: :member
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'login' =>    'sessions#new'
  post 'login' =>   'sessions#create'
  get 'logout' => 'sessions#destroy'
  post 'auth' => 'sessions#auth'
  post 'verify' => 'sessions#verify'

  get 'templates/property_modifier_config' => 'static_pages#property_modifier_config'
  get 'templates/ability_config' => 'static_pages#ability_config'
  get 'templates/charsheet_item' => 'static_pages#charsheet_item'
  get 'templates/char_equip_slot' => 'static_pages#char_equip_slot'
end

app/models/rule_set.rb
class RuleSet < ActiveRecord::Base
  # --------------------------------------------------------------------------------
  # Constants affecting some calculations in the system.
  # These constants should probably be moved to the database as properties of a
  # RuleSet.
  # --------------------------------------------------------------------------------

  def self.encumberance_factor(key)
    case key
      when :attack then 2
      when :parry then 1
      else 0
    end
  end

  def self.combat_value_factor
    1.0 / 25.0
  end

  def self.strength_factor_offset
    0.5
  end

  def self.strength_factor_gain
    0.01
  end

  def self.check_target_factor
    0.2
  end

  def self.container_factor(container)
    case container
      when 'backpack' then 3.5
      else 2.5
    end
  end

  def self.container_abbr(container)
    case container
      when 'backpack' then :str
      else :kon
    end
  end

  # --------------------------------------------------------------------------------
  # ActiveRecord settings
  # --------------------------------------------------------------------------------
  after_initialize :init_formulas

  validates :version, presence: true

  scope :active, -> { where(activated: true) }

  has_many :races
  has_many :birthsigns
  has_many :specializations
  has_many :skills
  has_many :resistances
  has_many :formulas
  has_many :item_prototypes
  has_many :spells

  # --------------------------------------------------------------------------------
  # Attention: The "attributes" collection is named "attrs" because ActiveRecords
  # already defines a method called "attributes"!
  # --------------------------------------------------------------------------------
  has_many :attrs, foreign_key: "rule_set_id", class_name: "Attribute"

  accepts_nested_attributes_for :formulas

  def needs_save?
    @needs_save
  end

  def formula_by_abbr(abbr)
    formulas.select { |f| f.abbr == abbr }.first
  end

  def property_by_abbr(abbr)
    Property.find_by(rule_set_id: self.id, abbr: abbr)
  end

  # Returns all valid properties for this rule set
  def properties
    Property.where(rule_set_id: self.id).order(:abbr)
  end

  # Returns an array containing arrays of arrays. First nest is sorted
  # by type, second by category, third contains actual ItemPrototypes
  # sorted by slot and name
  def items_by_type
    items_by_types = Hash.new { |h,k| h[k] =
                             Hash.new { |hi,ki| hi[ki] = [] } }
    # Sort items by type and category and put them in nested hashes
    self.item_prototypes.order(:type, :category, :slot, :name)
      .each do |item| 
        items_by_types[item.type][item.category] << item
      end
    items_by_types = items_by_types.values
    items_by_types.map! { |hash| hash.values }
    items_by_types
  end

  # how many level_count points are required to get a level-up
  def level_count_required
    10
  end

  def skill_type_max(type)
    case type
      when :major
        major_skill_count
      when :minor
        minor_skill_count
      else
        1000 # unlimited
    end
  end

  def RuleSet.latest
    RuleSet.active.order('version desc').first || RuleSet.new
  end

  private
    def init_formulas
      required_formulas = [
          {abbr: 'start_health', name: 'Start TP', formula: 'str+kon/2' },
          {abbr: 'max_stamina', name: 'Max Stamina', formula: 'str+wil+dex+kon-50*wounds_torso-50*wounds_belly', order: 0 },
          {abbr: 'mana_mult', name: 'Magicka Multiplier', formula: '1+mana_mult_buff-0.5*wounds_head', order: 1 },
          {abbr: 'max_mana', name: 'Max Magicka', formula: '(int*mana_mult).floor', order: 10},
          {abbr: 'hp_per_lvl', name: 'TP / Level', formula: 'kon/10' },

          # Behinderung
          {abbr: 'encumberance_from_health', name: 'Behinderung aus HP', formula:
                 'if health < 5; 6; elsif health < 11; 3; elsif health < 21; 1; else; 0; end',
           order: 4 },
          {abbr: 'encumberance_from_stamina', name: 'Behinderung aus Ausdauer', formula:
                 'case (stamina/max_stamina); when 0.5..1000; 0; when 0.25..0.5; 1; when 0.1..0.25; 3; else; 6; end',
           order: 4 },
          {abbr: 'encumberance_from_backpack', name: 'Behinderung aus Rucksack', formula:
                 'case (backpack_weight/max_backpack_weight); when 0..0.5; 0; when 0.5..0.75; 1; when 0.75..0.9; 4; else; 6; end',
           order: 4 },
          {abbr: 'encumberance_from_body', name: 'Behinderung aus Körpertraglast', formula:
                 'body_weight > max_body_weight ? 5 : 0',
           order: 4 },
          {abbr: 'encumberance', name: 'Behinderung', formula:
                 'wounds+encumberance_from_stamina+encumberance_from_backpack+encumberance_from_body', order: 5 },

          {abbr: 'max_backpack_weight', name: 'Max Rucksack Traglast', formula: 'str*3.5', order: 0},
          {abbr: 'max_body_weight', name: 'Max Körper Traglast', formula: 'kon*2.5', order: 0},
          {abbr: 'left_weapon_damage', name: 'Schaden linke Waffe', formula:
                 '(item.left_hand.min_damage+rolled_damage_left)*(item.left_hand.condition/100.0)*(0.5+str/100.0)*item.left_hand.speed'},
          {abbr: 'right_weapon_damage', name: 'Schaden rechte Waffe', formula:
                 '(item.right_hand.min_damage+rolled_damage_right)*(item.right_hand.condition/100.0)*(0.5+str/100.0)*item.right_hand.speed'},

          # Armor values of all slots
          # Head
          {abbr: 'armor_head', name: 'Rüstung Kopf', formula:
                 '0.1*armor_value(:head)', order: 5},
          # Chest
          {abbr: 'armor_chest', name: 'Rüstung Oberkörper', formula:
                 '0.3*armor_value(:chest)', order: 5},
          # Legs
          {abbr: 'armor_legs', name: 'Rüstung Beine', formula:
                 '0.1*armor_value(:legs)', order: 5},

          # Arms
          {abbr: 'armor_arms', name: 'Rüstung Arme', formula:
                 '0.1*armor_value(:arms)', order: 5},

          # Shoulders
          {abbr: 'armor_shoulders', name: 'Rüstung Schultern', formula:
                 '0.2*armor_value(:shoulders)', order: 5},

          # Füße
          {abbr: 'armor_feet', name: 'Rüstung Füße', formula:
                 '0.1*armor_value(:feet)', order: 5},

          # Schild
          {abbr: 'armor_shield', name: 'Rüstung Schild', formula:
                 '0.1*armor_value(:shield_hand)', order: 5},

          {abbr: 'armor_factor_armored', name: 'Rüstungssfaktor mit Rüstung', formula: '1.0/30.0', order: 0},
          {abbr: 'armor_factor_unarmored', name: 'Rüstungssfaktor ohne Rüstung', formula: '3.0/1000.0', order: 0},

          # Total armor for the character
          {abbr: 'total_armor', name: 'Gesamtrüstung', formula:
                 'armor_buff+armor_head+armor_chest+armor_legs+armor_arms+armor_shoulders+armor_feet+armor_shield',
                  order: 10},
          # Damage received
          {abbr: 'hp_loss', name: 'HP Verlust', formula:
                 '[damage_incoming-total_armor,damage_incoming*(1.0/3.0)].max', order: 20},

          # Evasion
          {abbr: 'evasion', name: 'Ausweichen', formula:
                 'evasion_buff+[(sch+dex+2*acr)/20,0].max-clumsiness-2*encumberance-2*wounds_head-wounds_torso-2*wounds_belly-3*wounds_leg'},

          # Hand-to-hand damage
          {abbr: 'hand_to_hand_damage_stamina', name: 'Faustkampfschaden gegen Ausdauer', formula: 'fau/2'},
          {abbr: 'hand_to_hand_damage_hp', name: 'Faustkampfschaden gegen HP', formula: 'fau*0.1'},

          # Laufweg
          {abbr: 'speed', name: 'Laufweg', formula: 'speed_buff+1+sch/12.0-encumberance-wounds_torso-wounds_belly-2*wounds_leg', order: 10},
          {abbr: 'speed_2', name: 'Laufweg 2', formula: 'speed_buff+speed*ath/40-encumberance-wounds_torso-wounds_belly-2*wounds_leg', order: 11},

          # Initiative
          {abbr: 'initiative', name: 'Initiative', formula: 'sch/5.0+initiative_roll-encumberance*2', order: 10},
      ]
      required_formulas.each do |req|
        if formula_by_abbr(req[:abbr]).nil?
          req[:formula] ||= '0'
          req[:rule_set] = self
          formulas.new(req)
          @needs_save = true
        end
      end
    end
end

app/controllers/rule_sets_controller.rb
class RuleSetsController < ApplicationController
  before_action :ensure_logged_in
  before_action :ensure_permitted, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_rule_set, only: [:show, :edit, :update, :destroy, :properties]

  add_breadcrumb "Regelsätze", :rule_sets_path

  layout 'with_sidebar'

  def index
    @rule_sets = RuleSet.all
  end

  def show
  end

  def new
    @rule_set = RuleSet.new
  end

  def edit
  end

  def properties
    @properties = @rule_set.attrs + @rule_set.skills + @rule_set.resistances
    respond_to do |format|
      format.json
    end
  end

  def create
    @rule_set = RuleSet.new(rule_set_params)

    respond_to do |format|
      if @rule_set.save
        format.html { redirect_to @rule_set, notice: 'Regelsatz erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @rule_set }
      else
        format.html { render :new }
        format.json { render json: @rule_set.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rule_set.update(rule_set_params)
        format.html { redirect_to edit_rule_set_url(@rule_set), notice: 'Regelsatz aktualisiert.' }
        format.json { render :show, status: :ok, location: @rule_set }
      else
        format.html { render :edit }
        format.json { render json: @rule_set.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rule_set.destroy
    respond_to do |format|
      format.html { redirect_to rule_sets_url, notice: 'Regelsatz gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule_set
      @rule_set = RuleSet.find(params[:id])
      if @rule_set.needs_save?
        @rule_set.save
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_set_params
      params.require(:rule_set).permit(:version, :activated,
          formulas_attributes: [:id, :name, :formula, :icon, :order])
    end

    def ensure_permitted
      unless current_user && current_user.has_role?(:gm)
        store_location
        redirect_to login_url
      end
    end
end

app/helpers/rule_sets_helper.rb
module RuleSetsHelper
end

app/views/rule_sets/_form.html.erb
<%= form_for(@rule_set) do |f| %>
  <%= render 'shared/error_messages', model: @rule_set %>

  <%= f.label :version %>
  <%= f.text_field :version, class: 'form-control' %>

  <h2>Formeln</h2>
  <h4>Gültige Variablen:</h4>
  <div>
    <% @rule_set.properties.each do |prop| %>
      <% path = prop.is_a?(Formula) ? '#' : edit_polymorphic_path([@rule_set, prop]) %>
      <%= link_to prop.abbr, path, title: prop.name, target: '_blank'  %>
    <% end %>
  </div>
  <div class="pseudo-table">
    <div>
      <h4 style="width: 150px">Name</h4>
      <h4>Kürzel</h4>
      <h4>Formel</h4>
      <h4 style="width: 100px">Sortierung</h4>
    </div>
    <%= f.fields_for :formulas do |ff| %>
      <div>
        <div>
          <%= ff.text_field :name, class: 'form-control' %>
        </div>
        <div>
          <%= ff.object.abbr %>
        </div>
        <div>
          <%= ff.text_field :formula, class: 'form-control' %>
        </div>
        <div>
          <%= ff.text_field :order, class: 'form-control' %>
        </div>
      </div>
    <% end %>
  </div>

  <%= f.label :activated, class: 'checkbox inline' do %>
    <%= f.check_box :activated %>
    <span>Regelsatz freigeben</span>
  <% end %>

  <div class="actions">
    <%= link_to "Zurück", rule_sets_path, class: "btn btn-primary" %>
    <%= f.submit "Speichern", class: "btn btn-primary" %>
    <% unless @rule_set.new_record? %>
      <%= link_to 'Löschen', @rule_set, method: :delete, class: 'btn',
                  data: { confirm: 'Bist du dir ganz sicher?' } %>
    <% end %>
  </div>
<% end %>

app/views/rule_sets/_links.html.erb
<div class="btn-group">
  <%= link_to "Attribute (#{@rule_set.attrs.count})", rule_set_attributes_path(@rule_set), class: 'btn' %>
  <%= link_to "Spezialisierungen (#{@rule_set.specializations.count})", rule_set_specializations_path(@rule_set), class: 'btn' %>
  <%= link_to "Skills (#{@rule_set.skills.count})", rule_set_skills_path(@rule_set), class: 'btn' %>
  <%= link_to "Rassen (#{@rule_set.races.count})", rule_set_races_path(@rule_set), class: 'btn' %>
  <%= link_to "Sternzeichen (#{@rule_set.birthsigns.count})", rule_set_birthsigns_path(@rule_set), class: 'btn' %>
  <%= link_to "Resistenzen (#{@rule_set.resistances.count})", rule_set_resistances_path(@rule_set), class: 'btn' %>
  <%= link_to "Items (#{@rule_set.item_prototypes.count})", rule_set_item_prototypes_path(@rule_set), class: 'btn' %>
  <%= link_to "Zaubersprüche (#{@rule_set.spells.count})", rule_set_spells_path(@rule_set), class: 'btn' %>
</div>

app/views/rule_sets/edit.html.erb
<h1>Regelsatz bearbeiten</h1>

<%= render 'links' %>
<%= render 'form' %>

app/views/rule_sets/index.html.erb
<h1>Regelsätze</h1>

<div class="pseudo-table">
  <div>
    <h4>Version</h4>
    <h4>Attribute</h4>
    <h4>Spezialisierungen</h4>
    <h4>Rassen</h4>
    <h4>Skills</h4>
    <h4>Sternzeichen</h4>
    <h4>Resistenzen</h4>
  </div>

  <% @rule_sets.each do |rule_set| %>
    <%= link_to current_user.has_role?(:gm) ?
                edit_rule_set_path(rule_set) :
                rule_set_path(rule_set) do %>
      <div><%= rule_set.version %></div>
      <div><%= rule_set.attrs.count %></div>
      <div><%= rule_set.specializations.count %></div>
      <div><%= rule_set.races.count %></div>
      <div><%= rule_set.skills.count %></div>
      <div><%= rule_set.birthsigns.count %></div>
      <div><%= rule_set.resistances.count %></div>
    <% end %>
  <% end %>
</div>

<% if current_user.has_role?(:gm) %>
  <div class="actions">
    <%= link_to 'Neuer Regelsatz', new_rule_set_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/rule_sets/new.html.erb
<h1>New Rule Set</h1>

<%= render 'form' %>

app/views/rule_sets/show.html.erb
<h1>Version <%= @rule_set.version %></h1>

<%= render 'links' %>

<div class="actions">
  <% if current_user.has_role?(:gm) %>
    <%= link_to 'Bearbeiten', edit_rule_set_path(@rule_set), class: 'btn' %>
  <% end %>
  <%= link_to 'Zurück', rule_sets_path, class: 'btn' %>
</div>